Dockerfile mimisation
jontze/cadency-rs pull request #69
Opened 2022-10-15 10:51 UTC by TeaDrinkingProgrammer

First of all, I want to say that this project looks really good: I wanted to make a Rust musicbot myself but when I saw this I thought: ¨this is exactly how I would do it if I had the time (and Rust know-how)". I thus started to look at what I could contribute and began with the Dockerfile, as it seemed to me that it could be smaller. It turns out it can be smaller!

For future reference,I tried:

- Alpine -> too much of a hassle to compile Rust to musl instead of glibc
- Compiling FFMPEG myself -> Makes a small image, but I am no expert at compilation soo to much of a risk of breaking in the future

In the end I settled on these changes:
- Using bitnami/minideb as a base. It turns out installing Python on this image makes it smaller than using the official python:3-slim image.
- Removing unnecessary Python build and develop dependencies
- Using the [static FFMPEG build from yt-dlp](https://github.com/yt-dlp/FFmpeg-Builds). Has the additional benifit of containing some yt-dlp specific fixes. Also offloads the compilation responsibility to them and is assured to work.

Size comparisons (no --squash used):
- Current image from ghcr.io: 631.05 MB
- New image: 248.48 MB

As a side-note, the version with the custom-compiled FFMPEG, came in at 229.4 MBs. The final image might be smaller or even bigger, because the image did not work yet, but I am not going to all that effort to safe 20-40 MBs.

## Notes:
Adding the squash flag made no difference, as the image has very few layers to begin with.  
The new image uses a staticly compiled FFMPEG, which makes architecture dependent. yt-dlps ffmpeg is compiled to both arm64 and amd64 though, so I included an if statement to download the correct version. This should make the new image compatible with both versions, which I think are the only architectures people are using realistically anyways.

2022-10-15 11:11 UTC, TeaDrinkingProgrammer commented
I tried building for arm on my pc but it gave an error on the first cargo build step, but this is likely a cross-compilation problem, not a problem with the new FFMPEG workflow

2022-10-15 18:15 UTC, jontze requested changes
LGTM! :rocket: 
Thank you for your contribution and I'm happy to hear that  people are using and enjoining the bot!

The big docker image was always something that annoyed me. So thanks for taking care about this. I wasn't aware of bitnami/minideb, so nice learning for me. :smile: 

Only one tiny styling thing:
I try to stick to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) with my commit messages in this repo. So it would be really nice if you reword your commit message to something like `chore(docker): ...`

But otherwise LGTM!

2022-10-17 20:14 UTC, jontze approved these changes
LGTM!

Just one small typo and we're ready to go, approving already.

2022-10-17 20:14 UTC, jontze commented on README.md
> +4. Install [ffmpeg](https://ffmpeg.org/). It is reccomended you install the [yt-dlp build](https://github.com/yt-dlp/FFmpeg-Builds), as this is used in the Docker image as well and includes additiona
```suggestion
4. Install [ffmpeg](https://ffmpeg.org/). It is recomended you install the [yt-dlp build](https://github.com/yt-dlp/FFmpeg-Builds), as this is used in the Docker image as well and includes additional bug-fixes.
```

2022-10-17 20:37 UTC, TeaDrinkingProgrammer commented
Apparently I had to merge the readme, all ready now

2022-10-17 20:42 UTC, merged